# ios/Podfile
# React Native iOS dependencies and PhlexPlayer native module

require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.0'

target 'PhlexMobile' do
  config = use_native_modules!
  use_react_native!(
    :path => '../node_modules/react-native',
    :app_path => '..'
  )

  # Local PhlexPlayer native module
  pod 'PhlexPlayer', :path => './LocalPods/PhlexPlayer'

  post_install do |installer|
    react_native_post_install(installer)
  end
end
