# ios/Podfile
# React Native iOS dependencies and PhlixPlayer native module

# Disable New Architecture for better compatibility with prebuilt binaries
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1'

target 'PhlixMobile' do
  config = use_native_modules!
  use_react_native!(
    :path => '../node_modules/react-native',
    :app_path => '..',
    :new_arch_enabled => false
  )

  # Local PhlixPlayer native module
  pod 'PhlixPlayer', :path => './LocalPods/PhlixPlayer'

  post_install do |installer|
    react_native_post_install(installer)
  end
end
